baseline: Your blogging assistant.
theme: hyde
output:
  formats:
    - name: netlify_redirects
      mediatype: text/plain
      extension: ""
keywords: Cecil, Static Site Generator, SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
postprocess:
  enabled: true
title: Stefan's Dev Journal
description: My private Software development journey
baseurl: /
canonicalurl: false
virtualpages:
  - path: admin
    title: Content Manager (Netlify CMS)
    layout: admin/index
    output: html
  - path: _redirects
    output: netlify_redirects
